version: "3.9"

services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/cargo_management
    depends_on:
      - mongo

  frontend:
    build: ./CargoManagement
    ports:
      - "4173:4173"  
    depends_on:
      - backend

volumes:
  mongo_data:
